export const ACTIONS = {
  // AUTH ACTIONS
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOAD_USER: 'LOADED_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  LOGOUT_AUTH: 'LOGOUT_AUTH',
  ACCOUNT_DELETE: 'ACCOUNT_DELETE',
  // PROFILE ACTIONS
  GET_PROFILE: 'GET_PROFILE',
  CREATE_PROFILE: 'CREATE_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  CLEAR_PROFILE: 'CLEAR_PROFILE',
  // ALERT ACTIONS
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT'
};
