export const ACTIONS = {
  // AUTH ACTIONS
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOAD_USER: 'LOADED_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  LOGOUT_AUTH: 'LOGOUT_AUTH',
  ACCOUNT_DELETE: 'ACCOUNT_DELETE',
  // PROFILE ACTIONS
  GET_PROFILE: 'GET_PROFILE',
  CREATE_PROFILE: 'CREATE_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  CLEAR_PROFILE: 'CLEAR_PROFILE',
  GET_ALL_PROFILES: 'ALL_PROFILES',
  GET_GITHUB_REPOS: 'GET_GITHUB_REPOS',
  // ALERT ACTIONS
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
  // POST ACTIONS
  GET_POSTS: 'GET_POSTS',
  POST_ERROR: 'POST_ERROR'
};
